<?php
	$server = "localhost:3306";
	$user = "root";
	$pass = "";
	$db = "batangoble_db";
	$conn = mysqli_connect($server, $user, $pass, $db);
	if(!$conn) die(mysqli_error($conn));

	$query = "CREATE TABLE STUDENT
	(
		APP_YR VARCHAR(4) NOT NULL,
		DATE_STARTED DATE,
		STUD_SEMESTER VARCHAR(20),
		STUD_ACADYEAR VARCHAR(20),
		STUD_LASTNAME VARCHAR(100) NOT NULL,
		STUD_FIRSTNAME VARCHAR(100) NOT NULL,
		STUD_MIDDLEINT VARCHAR(5),
		STUD_NICKNAME VARCHAR(100),
		STUD_BIRTHDAY DATE,
		STUD_ADDRESS VARCHAR(150),
		STUD_AGE VARCHAR(20) NOT NULL,
		STUD_SEX VARCHAR(10) NOT NULL,
		STUD_SCHEDTIME VARCHAR(50),
		STUD_SCHEDDAY VARCHAR(50),

		FATHER_LASTNAME VARCHAR(100),
		FATHER_FIRSTNAME VARCHAR(100),
		FATHER_MIDDLEINT VARCHAR(5),
		FATHER_TYPE VARCHAR(20),
		FATHER_AGE VARCHAR(20),
		FATHER_BIRTHDAY DATE,
		FATHER_OCCUPATION VARCHAR(50),
		FATHER_OFFICE VARCHAR(200),
		FATHER_CONTACT VARCHAR(11),
		FATHER_EMAIL VARCHAR(50),

		MOTHER_LASTNAME VARCHAR(100),
		MOTHER_FIRSTNAME VARCHAR(100),
		MOTHER_MIDDLEINT VARCHAR(5),
		MOTHER_TYPE VARCHAR(20),
		MOTHER_AGE VARCHAR(20),
		MOTHER_BIRTHDAY DATE,
		MOTHER_OCCUPATION VARCHAR(50),
		MOTHER_OFFICE VARCHAR(200),
		MOTHER_CONTACT VARCHAR(11),
		MOTHER_EMAIL VARCHAR(50),

		GUARDIAN_LASTNAME VARCHAR(100),
		GUARDIAN_FIRSTNAME VARCHAR(100),
		GUARDIAN_MIDDLEINT VARCHAR(5),
		GUARDIAN_TYPE VARCHAR(20),
		GUARDIAN_AGE VARCHAR(20),
		GUARDIAN_BIRTHDAY DATE,
		GUARDIAN_OCCUPATION VARCHAR(50),
		GUARDIAN_OFFICE VARCHAR(200),
		GUARDIAN_CONTACT VARCHAR(11),
		GUARDIAN_RELATION VARCHAR(50),

		MEDICALBG_ONE VARCHAR(1000),
		MEDICALBG_TWO VARCHAR(1000),
		MEDICALBG_THREE VARCHAR(1000),
		MEDICALBG_FOUR VARCHAR(1000),
		MEDICALBG_FIVE VARCHAR(1000),
		MEDICALBG_SIX VARCHAR(1000),
		MEDICALBG_SEVEN VARCHAR(1000),

		EMER_LASTNAME VARCHAR(100) NOT NULL,
		EMER_FIRSTNAME VARCHAR(100) NOT NULL,
		EMER_MIDDLEINT VARCHAR(5),
		EMER_ADDRESS VARCHAR(100) NOT NULL,
		EMER_CONTACT VARCHAR(11) NOT NULL,
		EMER_RELATION VARCHAR(50) NOT NULL,

		MODE_PAY VARCHAR(20) NOT NULL,
		AMT_PAID NUMERIC(8),
		DATE_PAID DATE,
		OR_NUM NUMERIC(20)

	)";
	mysqli_query($conn, $query);

	$query = "INSERT INTO STUDENT VALUES
		('2015', '2015-04-06', NULL, NULL, 'Anongos', 'Seth Chadlos', 'B', 'Chadlos', NULL, '1A29 BSU Compound, La Trinidad', '4', 'M', '1pm-3pm','Afternoon','Anongos','Samuel', 'F', NULL, '34', '1981-01-24', 'NGO', 'Cordillera Peoples Alliance', '09291477508', NULL,'Anongos', 'Abigail', 'B', NULL, '33', '1981-08-27','NGO','Cordillera Peoples Alliance','09199927369',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'Yes. Medication for asthma, as needed, like when there are symptoms of attack or having an attack. (Ex: beta-agonist; lagundi or nebulisation)','Dust and smoke. He also has a coughing fit after strenous physical activity due to his asthma. If this happens we just let him rest first, observe. Di agad nebulise','none observe, so far','Not anymore this year. He doesnt nap in the afternoon anymore (2pm-4pm dati) but goes to bed early at 8pm-8:30pm','Not, so far. Our observation of recent is, madaling mapikon','None', NULL,'Bengwayan','Grace', NULL, 'c/o BSU Administration', '09205417031','Grandmother','Monthly', NULL, NULL, NULL ),
		 ('2015', '2015-09-04', NULL, NULL, 'Bagsic', 'Denniesse', 'C', 'Niezza', NULL, '329A Pinsao Proper, Tamawan Village, Baguio City 2600', '4', 'f', NULL, NULL, 'Bagsic', 'James Benedict', 'E', NULL, '35', '1975-08-03', 'Administrative staff', 'SPMB, UP Baguio', '09276197136', NULL, 'Bagsic', 'Ofelia', 'C', NULL, '33', '1981-06-27', NULL, NULL, '09063751135', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'None', 'None', 'Yes, cockroaches', 'Yes, 1pm onwards', 'No', 'None', NULL, 'Bagsic', 'James Benedict', 'E', '329A Pinsao Proper, Tamawan Village, Baguio City 2600', '09276137136', 'Father', 'Drop-in', NULL, NULL, NULL);";
	mysqli_query($conn, $query);

	$query = "CREATE TABLE PAYMENT(
		APP_YR VARCHAR(4) NOT NULL,
		DATE_STARTED DATE,
		STUD_LASTNAME VARCHAR(100) NOT NULL,
		STUD_FIRSTNAME VARCHAR(100) NOT NULL,
		STUD_MIDDLEINT VARCHAR(5),
		STUD_AGE VARCHAR(20) NOT NULL,
		STUD_SEX VARCHAR(10) NOT NULL,
		FATHER_TYPE VARCHAR(20),
		MOTHER_TYPE VARCHAR(20),
		GUARDIAN_TYPE VARCHAR(20),
	)";
	mysqli_query($conn, $query);



	$query = "CREATE TABLE PAYMENT(
		PAYMENT_TYPE VARCHAR(50) NOT NULL,
		PAYMENT_AMOUNT NUMERIC(8,2) NOT NULL,
		OUT_BAL NUMERIC(8,2),
		AMT_PAID NUMERIC(8,2),
		DATE_PAID DATE,
		OR_NUM NUMERIC(11),
		STUD_NAME VARCHAR(10) NOT NULL,

		/* DEPENDS ON THE TYPE OF ENROLLMENT STUFFERS
		LOAN_YEAR VARCHAR(10) NOT NULL,
		LOAN_SEM VARCHAR(3) NOT NULL,
		*/ 

		DATE_ADDED DATE NOT NULL,
		PAYMENT_REMARKS VARCHAR(200)
	)";
	mysqli_query($conn, $query);


	$query = "CREATE TABLE SA
	(
		SA_STUDNUM VARCHAR(10) NOT NULL,
		SA_LASTNAME VARCHAR(100) NOT NULL,
		SA_FIRSTNAME VARCHAR(100) NOT NULL,
		SA_MIDDLE VARCHAR(10),
		SA_COURSE VARCHAR(35) NOT NULL,
		SA_COLLEGE VARCHAR(10) NOT NULL,
		SA_YEAR VARCHAR(6) NOT NULL,
		SA_SEX VARCHAR(10) NOT NULL,
		SA_ADDRESS VARCHAR(100) NOT NULL,
		SA_EMAIL VARCHAR(50) NOT NULL,
		SA_CONTACT VARCHAR(11) NOT NULL,
		SA_HOURS VARCHAR(10) NOT NULL

	)";
	mysqli_query($conn, $query);

	$query = "CREATE TABLE STUD_HISTORY(
		STUD_LNAME VARCHAR(100) NOT NULL,
		STUD_FNAME VARCHAR(100) NOT NULL,
		STUD_MIDINT VARCHAR(100) NOT NULL,
		PAYMENT_MODE VARCHAR(50) NOT NULL,
		AMT_PAID NUMERIC(8),
		DATE_PAID DATE,
		OR_NUM NUMERIC(20),
		APP_YEAR VARCHAR(10) NOT NULL
	)";
	mysqli_query($conn, $query);
	mysqli_query($conn, $query);

	$query = "INSERT INTO STUD_HISTORY VALUES
		('Anongos','Seth Chadlos', 'B', 'Monthly',NULL,NULL,NULL,'2015')";
	mysqli_query($conn, $query);

?>